### ISSUE TITLE
Skell downloader not found

### ISSUE THREAD

**Issue by yaoberh** [abdnh/anki-incontext#8]
Hey! So my installation doesn't find Skell downloader. 
Found your other repository with this name, put it into the incontext folder but this doesn't fix the issue.
What should I do?
```

When loading '⁨InContext - Learn vocabulary in context⁩':
⁨Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/addons.py", line 244, in loadAddons
    __import__(addon.dir_name)
  File "/home/yaoberh/.local/share/Anki2/addons21/incontext/__init__.py", line 14, in <module>
    from .incontext_dialog import InContextDialog
  File "/home/yaoberh/.local/share/Anki2/addons21/incontext/incontext_dialog.py", line 9, in <module>
    from .providers import get_languages, get_providers_for_language, get_sentence
  File "/home/yaoberh/.local/share/Anki2/addons21/incontext/providers/__init__.py", line 14, in <module>
    from .skell import SkellProvider
  File "/home/yaoberh/.local/share/Anki2/addons21/incontext/providers/skell.py", line 3, in <module>
    from .vendor.skell_downloader import SkellDownloader
ModuleNotFoundError: No module named 'incontext.providers.vendor.skell_downloader'
```

Have a great day :)

**Comment by yaoberh** [comment]
Had to downgrade anki to 2.1.50, working now :)

**Comment by abdnh** [comment]
Hmm, Skell downloader is working fine for me on ⁨2.1.54. I'm surprised downgrading fixed the issue.
Did you get your installation from the [releases page](https://github.com/abdnh/anki-incontext/releases/tag/0.1)?
